
// for all data get from users
export const GET_DATA_PRODUCTS_REQUEST="GET_DATA_PRODUCTS_REQUEST";
export const GET_DATA_PRODUCTS_SUCCESS="GET_DATA_PRODUCTS_SUCCESS";
export const GET_DATA_PRODUCTS_FAILURE="GET_DATA_PRODUCTS_FAILURE";

// for all data add =>post from users
export const ADD_DATA_PRODUCTS_REQUEST="ADD_DATA_PRODUCTS_REQUEST";
export const ADD_DATA_PRODUCTS_SUCCESS="ADD_DATA_PRODUCTS_SUCCESS";
export const ADD_DATA_PRODUCTS_FAILURE="ADD_DATA_PRODUCTS_FAILURE";

// for all singleusers data
export const SINGLE_DATA_PRODUCTS_REQUEST="SINGLE_DATA_PRODUCTS_REQUEST";
export const SINGLE_DATA_PRODUCTS_SUCCESS="SINGLE_DATA_PRODUCTS_SUCCESS";
export const SINGLE_DATA_PRODUCTS_FAILURE="SINGLE_DATA_PRODUCTS_FAILURE";


// for all delete users data
export const DELETE_DATA_PRODUCTS_REQUEST="DELETE_DATA_PRODUCTS_REQUEST";
export const DELETE_DATA_PRODUCTS_SUCCESS="DELETE_DATA_PRODUCTS_SUCCESS";
export const DELETE_DATA_PRODUCTS_FAILURE="DELETE_DATA_PRODUCTS_FAILURE";

// get cart
export const GET_CART="GET_CART";

// for cart add data
export const ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST";

// for cart remove data
export const REMOVE_TO_CART_REQUEST="REMOVE_TO_CART_REQUEST";

