// for all data add =>post from users
export const ADD_DATA_CHECKOUT_REQUEST="ADD_DATA_CHECKOUT_REQUEST";
export const ADD_DATA_CHECKOUT_SUCCESS="ADD_DATA_CHECKOUT_SUCCESS";
export const ADD_DATA_CHECKOUT_FAILURE="ADD_DATA_CHECKOUT_FAILURE";

// for all data get from users
export const GET_DATA_CHECKOUT_REQUEST="GET_DATA_CHECKOUT_REQUEST";
export const GET_DATA_CHECKOUT_SUCCESS="GET_DATA_CHECKOUT_SUCCESS";
export const GET_DATA_CHECKOUT_FAILURE="GET_DATA_CHECKOUT_FAILURE";